var allRestaurants = [
  {
    "name": "Polaris Gourmet",
    "address": "#B1-24, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/polaris-gourmet",
    "phone": 62206818,
    "price": 25,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "The Lawn",
    "address": "#B1-11, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/the-lawn-cafe-axa-tower",
    "phone": 65348749,
    "price": 13,
    "cuisine": "Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Kotobuki Japanese Restaurant",
    "address": "#01-17/18/19/20, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/kotobuki-japanese-restaurant-8-shenton-way",
    "phone": 63279590,
    "price": 45,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Saravanaa Bhavan",
    "address": "#B1-22, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/saravanaa_bhavan_robinson_road/",
    "phone": 62244525,
    "price": 19,
    "cuisine": "Indian",
    "halal": false,
    "veg": true
  },
  {
    "name": "Jaggis",
    "address": "#B1-19, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "B",
    "website": "http://www.hungrygowhere.com/singapore/jaggi-s-northern-indian-cuisine-tanjong-pagar-raffles-place/",
    "phone": 62966141,
    "price": 10,
    "cuisine": "Indian",
    "halal": false,
    "veg": true
  },
  {
    "name": "L`Euphoriz",
    "address": "#01-21, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/leuphoriz",
    "phone": 62218785,
    "price": 15,
    "cuisine": "Vietnamese",
    "halal": false,
    "veg": true
  },
  {
    "name": "Folks Collective",
    "address": "#01-07/08/12, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/folks-collection-axa-tower",
    "phone": 62273487,
    "price": 25,
    "cuisine": "Thai",
    "halal": false,
    "veg": true
  },
  {
    "name": "Harry's at Shenton Way",
    "address": "#01-15/18/23, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/harry_s_shenton_way/",
    "phone": 63277250,
    "price": 20,
    "cuisine": "Western, Italian, American, Mexican",
    "halal": false,
    "veg": true
  },
  {
    "name": "Aglio Olio",
    "address": "#B1-14, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/aglio_olio_shenton_way/",
    "phone": 63273622,
    "price": 15,
    "cuisine": "Italian",
    "halal": false,
    "veg": true
  },
  {
    "name": "Han Ka Ram Korean Restaurant",
    "address": "#B1-20, AXA Tower, 8 Shenton Way, 068811",
    "zip": 68811,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/han-ka-ram",
    "phone": 62230373,
    "price": 15,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "PastaMania",
    "address": "#01-07, CPF Building, 79 Robinson Road, 068897",
    "zip": 68897,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/pasta-mania-cpf-building",
    "phone": 62236964,
    "price": 12,
    "cuisine": "Italian, Western",
    "halal": true,
    "veg": true
  },
  {
    "name": "The China Club",
    "address": "52F, Capital Tower, 168 Robinson Road, 068912",
    "zip": 68912,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/the-china-club-singapore",
    "phone": 68202388,
    "price": 45,
    "cuisine": "Chinese",
    "halal": false,
    "veg": true
  },
  {
    "name": "SupperMan",
    "address": "#01-06, Maxwell Chamber, 32 Maxwell Road, 069115",
    "zip": 69115,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/superman",
    "phone": 62240338,
    "price": 25,
    "cuisine": "Fusion, Western",
    "halal": false,
    "veg": true
  },
  {
    "name": "Otto Ristorante",
    "address": "32 MAXWELL ROAD, #01-02 WHITE HOUSE",
    "zip": 69115,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/otto-ristorante-tanjong-pagar-raffles-place/",
    "phone": 62276819,
    "price": 45,
    "cuisine": "Italian, Western",
    "halal": false,
    "veg": true
  },
  {
    "name": "Moi Lum Restaurant",
    "address": "#01-01, Airview Building, 38 Maxwell Road, 069116",
    "zip": 69116,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/moi-lum-restaurant",
    "phone": 62262283,
    "price": 26,
    "cuisine": "Chinese",
    "halal": false,
    "veg": true
  },
  {
    "name": "The Soup Spoon",
    "address": "#B1-31, Tanjong Pagar MRT Station, 120 Maxwell Road, 069119",
    "zip": 69119,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/the_soup_spoon_tanjong_pagar/",
    "phone": 62220272,
    "price": 12,
    "cuisine": "Western",
    "halal": true,
    "veg": true
  },
  {
    "name": "Bukang Tuna Restaurant",
    "address": "#01-06, Reddot Traffic Building, 28 Maxwell Road, 069120",
    "zip": 69120,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/bukang_tuna_tuna/",
    "phone": 63274123,
    "price": 31,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Plate",
    "address": "Level 3, Carlton City Hotel, 1 Gopeng Street, 078862",
    "zip": 78862,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/plate-anson-tanjong-pagar/",
    "phone": 0,
    "price": 45,
    "cuisine": "Singaporean",
    "halal": true,
    "veg": true
  },
  {
    "name": "Sushi Kou",
    "address": "#01-16, Orchid Hotel, 1 Tras Link, 078867",
    "zip": 78867,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/sushi-kou",
    "phone": 64448433,
    "price": 45,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Keisuke Tonkotsu King",
    "address": "#01-19, Orchid Hotel, 1 Tras Street, 078867",
    "zip": 78867,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/keisuke-tonkotsu-king-anson-tanjong-pagar/",
    "phone": 66360855,
    "price": 17,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Teppei Japanese Restaurant",
    "address": "#01-18, Orchid Hotel, 1 Tras Link, 078867",
    "zip": 78867,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/teppei-japanese-restaurant",
    "phone": 62227363,
    "price": 30,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Menya Sanji",
    "address": "#01-14 ORCHID HOTEL, 1 TRAS LINK, 078867",
    "zip": 78867,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/sanji-ramen-anson-tanjong-pagar/",
    "phone": 66048891,
    "price": 18,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Keisuke Gyoza King",
    "address": "#01-15, Orchid Hotel, 1 Tras Link, 078867",
    "zip": 78867,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/gyoza-king-anson-tanjong-pagar/",
    "phone": 66046674,
    "price": 16,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Ramyun & Soju",
    "address": "#01-03, ORCHID HOTEL, 1 TRAS LINK, 078867",
    "zip": 78867,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/ramyun-soju",
    "phone": 0,
    "price": 16,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Two Blur Guys",
    "address": "1 TRAS LINK, #01-13 ORCHID HOTEL, 078867",
    "zip": 78867,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/two-blur-guys",
    "phone": 66364183,
    "price": 20,
    "cuisine": "American, Western",
    "halal": false,
    "veg": true
  },
  {
    "name": "Sakari Sushi",
    "address": "1 TRAS LINK, #01-05 ORCHID HOTEL, 078867",
    "zip": 78867,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/sakari-sushi-restaurant",
    "phone": 97397607,
    "price": 28,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Pizzeria L� Operetta",
    "address": "12 GOPENG STREET, #01-78, ICON VILLAGE, 078877",
    "zip": 78877,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/Pizzeria_L_Operetta/",
    "phone": 62229487,
    "price": 31,
    "cuisine": "Italian",
    "halal": true,
    "veg": true
  },
  {
    "name": "Spice Grill",
    "address": "12 GOPENG STREET, #01-82/83, ICON VILLAGE, 078877",
    "zip": 78877,
    "cleanliness_grade": "A",
    "website": "https://foursquare.com/v/spice-grill/55324173498e91f7854e1678",
    "phone": 81112063,
    "price": 15,
    "cuisine": "Indian",
    "halal": true,
    "veg": true
  },
  {
    "name": "Yolo",
    "address": "12 GOPENG STREET, #01-01/04, ICON VILLAGE, 078877",
    "zip": 78877,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/yolo-food",
    "phone": 62213029,
    "price": 12,
    "cuisine": "Mexican, Western",
    "halal": false,
    "veg": true
  },
  {
    "name": "Sakae Sushi",
    "address": "12 GOPENG STREET, #01-10 ICON VILLAGE, 078877",
    "zip": 78877,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/sakae_sushi_icon_village/",
    "phone": 65349935,
    "price": 18,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Sushi Mitsuya",
    "address": "#01-01, 60 Tras Street, 078999",
    "zip": 78999,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/sushi-mitsuya",
    "phone": 64382608,
    "price": 45,
    "cuisine": "Japanese",
    "halal": true,
    "veg": false
  },
  {
    "name": "Fleur de Sel Le Restaurant",
    "address": "64 Tras Street, 079003",
    "zip": 79003,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/fleur-de-sel",
    "phone": 62226861,
    "price": 45,
    "cuisine": "French, Western",
    "halal": false,
    "veg": true
  },
  {
    "name": "May May",
    "address": "Tanjong Pagar Conservation Area, 65 Tras Street, 079004",
    "zip": 79004,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/may-may-sg",
    "phone": 62214698,
    "price": 40,
    "cuisine": "Fusion",
    "halal": false,
    "veg": false
  },
  {
    "name": "Brasserie Gavroche",
    "address": "66 Tras Street, 079005",
    "zip": 79005,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/brasserie-gavroche",
    "phone": 62258266,
    "price": 45,
    "cuisine": "French, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Violet Herbs",
    "address": "Tanjong Pagar Conservation Area, 81 Tras Street, 079020",
    "zip": 79020,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/violet-herbs",
    "phone": 62213988,
    "price": 45,
    "cuisine": "French, Italian, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Sushi Burrito",
    "address": "#01-06, 100AM, 100 Tras Street, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/sushi-burito",
    "phone": 65436860,
    "price": 17,
    "cuisine": "Japanese, Mexican",
    "halal": false,
    "veg": true
  },
  {
    "name": "Pagi Sore Indonesian Restaurant",
    "address": "#02-15/28, 100AM, 100 Tras Street, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/pagi-sore",
    "phone": "�66361373, 62256002",
    "price": 25,
    "cuisine": "Indonesian, Malay, Indonesian",
    "halal": true,
    "veg": false
  },
  {
    "name": "YAYOI 100AM",
    "address": "#03-12, 100AM, 100 Tras Street, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/yayoiken-japanese-restaurant",
    "phone": 66948809,
    "price": 22,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Ramen Keisuke Tori King",
    "address": "#01-19 , 1 Tras Link, Orchid Hotel Singapore, 078867",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/keisuke-tonkotsu-king-anson-tanjong-pagar/",
    "phone": 66046861,
    "price": 18,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Ramen Keisuke Tori King",
    "address": "#03-15, 100AM, 100 Tras Street, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/ramen-keisuke-tori-king",
    "phone": 66046861,
    "price": 18,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Imperial Treasure Noodle & Congee House",
    "address": "#02-10/11, 100AM, 100 Tras Street, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/imperial-treasure-noodle--congee-house",
    "phone": 65436668,
    "price": 28,
    "cuisine": "Chinese",
    "halal": false,
    "veg": true
  },
  {
    "name": "Sodam Korean Restaurant and Bar",
    "address": "#01-08, 100AM, 100 Tras Street, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/sodam-so-delicious-korean-restaurant-bar",
    "phone": "68846884, 64440090",
    "price": 32,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "The Public Izakaya",
    "address": "100 TRAS STREET, #01-09 100 AM, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/the-public-izakaya",
    "phone": 66049622,
    "price": 41,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Tossz",
    "address": "100 Tras Street, #02-25, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "https://www.yelp.com.sg/biz/tossz-salads-singapore",
    "phone": 65366280,
    "price": 10,
    "cuisine": "Salads",
    "halal": true,
    "veg": false
  },
  {
    "name": "Shinkansen",
    "address": "100 Tras Street, #03-22, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/shinkansen-2",
    "phone": 0,
    "price": 15,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Zzapi Pizza Bar",
    "address": "100 TRAS STREET, #01-11, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/zzapi-pizza-bar-anson-tanjong-pagar/",
    "phone": 0,
    "price": 30,
    "cuisine": "Italian, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Japanese Restaurant Yayoiken",
    "address": "100 TRAS STREET, #03-12, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/yayoiken-anson-tanjong-pagar/",
    "phone": 65436248,
    "price": 30,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Soup Stock Tokyo",
    "address": "100 TRAS STREET, #02-27B 100 AM, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/soup-stock-tokyo-100am",
    "phone": 0,
    "price": 12,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Koufu Food Court @ 100 AM",
    "address": "100 TRAS STREET, #04, 100 AM, 079027",
    "zip": 79027,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/koufu-anson-tanjong-pagar/",
    "phone": 0,
    "price": 25,
    "cuisine": "Japanese, Vietnamese, Indian, Thai, Chinese, Korean, Japanese, Indonesian",
    "halal": true,
    "veg": true
  },
  {
    "name": "Chowon Garden Korean Restaurant",
    "address": "#01-01, 2 Peck Seah Street, 079305",
    "zip": 79305,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/chowon_garden_korean_restaurant/",
    "phone": 62251317,
    "price": 25,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Cove 99",
    "address": "72 Peck Seah Street, 079329",
    "zip": 79329,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/cove99",
    "phone": 62240991,
    "price": 22,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Whole Earth Peranakan Thai Vegetarian Restaurant",
    "address": "76 Peck Seah Street, 079331",
    "zip": 79331,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/whole_earth_peck_seah_street/",
    "phone": 63233308,
    "price": 28,
    "cuisine": "Peranakan",
    "halal": false,
    "veg": false
  },
  {
    "name": "Charcoal Pit",
    "address": "15 Enggor St, 079716",
    "zip": 79716,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/charcoal-pit",
    "phone": 88225991,
    "price": 20,
    "cuisine": "American, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Two Men Bagel House",
    "address": "16 ENGGOR STREET, #01-12 ALTEZ, 079717",
    "zip": 79717,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/two-men-bagel-house",
    "phone": 65094125,
    "price": 11,
    "cuisine": "American, Western",
    "halal": false,
    "veg": true
  },
  {
    "name": "Bratworks - The German Imbiss",
    "address": "16 ENGGOR STREET, #01-01 ALTEZ, 079717",
    "zip": 79717,
    "cleanliness_grade": "A",
    "website": "https://www.facebook.com/bratworksSG/",
    "phone": 85113545,
    "price": 15,
    "cuisine": "German",
    "halal": false,
    "veg": false
  },
  {
    "name": "The Public Izakaya 2",
    "address": "16 ENGGOR STREET, #01-14 ALTEZ, 079717",
    "zip": 79717,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/2-the-public-izakaya-2",
    "phone": 63339622,
    "price": 20,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "The Quarters",
    "address": "16 ENGGOR STREET, #01-09 ALTEZ, 079717",
    "zip": 79717,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/the-quarters",
    "phone": 68344174,
    "price": 16,
    "cuisine": "Singaporean",
    "halal": false,
    "veg": true
  },
  {
    "name": "Munch Saladsmith",
    "address": "16 ENGGOR STREET, #01-10 ALTEZ, 079717",
    "zip": 79717,
    "cleanliness_grade": "A",
    "website": "https://www.yelp.com.sg/biz/munch-saladsmith-singapore-5",
    "phone": 65093609,
    "price": 14,
    "cuisine": "American, Western, Salads",
    "halal": false,
    "veg": true
  },
  {
    "name": "Hakumai Sushi & Omakase",
    "address": "#01-50?A, International Plaza, 10 Anson Road, 079903",
    "zip": 79903,
    "cleanliness_grade": "B",
    "website": "http://www.hungrygowhere.com/singapore/hakumai-sushi-omakase-anson-tanjong-pagar/",
    "phone": "62244790?",
    "price": 45,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Meii Sushi",
    "address": "#02-54, International Plaza, 10 Anson Road, 079903",
    "zip": 79903,
    "cleanliness_grade": "B",
    "website": "http://www.hungrygowhere.com/singapore/Meii_Sushi_Restaurant__International_Plaza_/",
    "phone": 62203466,
    "price": 45,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Bimi Kaiho Restaurant",
    "address": "#02-28, International Plaza, 10 Anson Road, 079903",
    "zip": 79903,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/bimi-kaiho-japanese-restaurant",
    "phone": 62202262,
    "price": 20,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Ko Ryo Jeong Restaurant",
    "address": "#02-59, International Plaza, 10 Anson Road, 079903",
    "zip": 79903,
    "cleanliness_grade": "B",
    "website": "http://www.hungrygowhere.com/singapore/ko_ryo_jeong_restaurant/",
    "phone": 63243121,
    "price": 30,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Shin Nichi Japanese Restaurant",
    "address": "#02-35, International Plaza, 10 Anson Road, 079903",
    "zip": 79903,
    "cleanliness_grade": "B",
    "website": "http://www.hungrygowhere.com/singapore/shin_nichi_japanese_restaurant_international_plaza/",
    "phone": 62217575,
    "price": 17,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "The Wicked Garlic",
    "address": "#01-37, International Plaza, 10 Anson Road, 079903",
    "zip": 79903,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/the-wicked-garlic",
    "phone": 85092942,
    "price": 15,
    "cuisine": "Italian",
    "halal": false,
    "veg": true
  },
  {
    "name": "Brothers Ramen",
    "address": "#01-20, International Plaza, 10 Anson Road, 079903",
    "zip": 79903,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/brothers-ramen",
    "phone": 91793607,
    "price": 15,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Kan Sushi",
    "address": "#02-54, International Plaza, 10 Anson Road, 079903",
    "zip": 79903,
    "cleanliness_grade": "B",
    "website": "https://www.facebook.com/kansushi/",
    "phone": 62213678,
    "price": 25,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Tonkin Authentic Vietnamese Restaurant",
    "address": "70 ANSON ROAD, #01-03/04 HUB SYNERGY POINT, 079905",
    "zip": 79905,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/tonkin-authentic-vietnamese-cuisine",
    "phone": 62234813,
    "price": 26,
    "cuisine": "Vietnamese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Cafe 2000",
    "address": "81 ANSON ROAD, #01-00, M HOTEL, 079908",
    "zip": 79908,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/cafe-2000-m-hotel",
    "phone": 65006112,
    "price": 43,
    "cuisine": "Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Hokkaido Sushi Restaurant",
    "address": "9F, M Hotel, 81 Anson Road, 079908",
    "zip": 79908,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/hokkaido_sushi_restaurant/",
    "phone": 62213075,
    "price": 45,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "The Buffet",
    "address": "Level 2, M Hotel, 81 Anson Road, 079908",
    "zip": 79908,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/the_buffet/",
    "phone": "62241133, 65006116",
    "price": 45,
    "cuisine": "International",
    "halal": true,
    "veg": true
  },
  {
    "name": "Rocky Master",
    "address": "60 Anson Rd, 079914",
    "zip": 79914,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/Rocky_Master__MapleTree_Anson_/",
    "phone": 62245220,
    "price": 30,
    "cuisine": "Western, Fusion",
    "halal": true,
    "veg": true
  },
  {
    "name": "Hakata Ikkousha",
    "address": "#01-104, Hdb-central Area, 7 Tanjong Pagar Plaza, 081007",
    "zip": 81007,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/hakata-ikkousha-cantonment-tanjong-pagar-chinatown/",
    "phone": 65381880,
    "price": 21,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Socks & Pans",
    "address": "7 TANJONG PAGAR PLAZA, #01-108, 081007",
    "zip": 81007,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/socks-pans",
    "phone": 65363310,
    "price": 10,
    "cuisine": "Western, Italian",
    "halal": false,
    "veg": true
  },
  {
    "name": "The Salad Corner",
    "address": "1 Tanjong Pagar Plaza, 082001",
    "zip": 82001,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/the-salad-corner-1",
    "phone": 82020522,
    "price": 10,
    "cuisine": "Salad",
    "halal": true,
    "veg": true
  },
  {
    "name": "His.tori",
    "address": "20/22 Tanjong Pagar Road, 088443",
    "zip": 88443,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/His_tori_Japanese_BBQ___Korean_Casual_Dining/",
    "phone": 62246539,
    "price": 23,
    "cuisine": "Fusion, Japanese, Korean",
    "halal": false,
    "veg": true
  },
  {
    "name": "Han Kook Gwan Korean Restaurant",
    "address": "26 Tanjong Pagar Road, 088449",
    "zip": 88449,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/han-kook-gwan-korean-restaurant",
    "phone": 62242881,
    "price": 42,
    "cuisine": "Korean",
    "halal": false,
    "veg": true
  },
  {
    "name": "Capricci",
    "address": "27 Tanjong Pagar Road, 088450",
    "zip": 88450,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/capricci",
    "phone": 62216761,
    "price": 30,
    "cuisine": "Italian, Western, Wine",
    "halal": true,
    "veg": true
  },
  {
    "name": "2D1N Soju Bang",
    "address": "#01-01, 44/45/46 Tanjong Pagar Road, 088467",
    "zip": 88467,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/2d1n-soju-bang-korean-bbq-buffet",
    "phone": 62276033,
    "price": 24,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Fisher Man Bok",
    "address": "58 Tanjong Pagar Road, 088479",
    "zip": 88479,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/Manbok_Korean_Seafood_Restaurant/",
    "phone": 62246061,
    "price": 15,
    "cuisine": "Korean, Seafood",
    "halal": true,
    "veg": false
  },
  {
    "name": "Cumi Bali Indonesian Restaurant",
    "address": "66 Tanjong Pagar Road, 088487",
    "zip": 88487,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/cumi-bali",
    "phone": 62206619,
    "price": 21,
    "cuisine": "Indonesian, Malay, Indonesian",
    "halal": true,
    "veg": false
  },
  {
    "name": "Superstar K",
    "address": "75 Tanjong Pagar Road, 088496",
    "zip": 88496,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/super-star-k-korean-bbq",
    "phone": 62240504,
    "price": 43,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Supulae Restaurant",
    "address": "80 Tanjong Pagar Road, 088501",
    "zip": 88501,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/supulae-korean-bbq-restaurant",
    "phone": 62252248,
    "price": 30,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Xin Mei Le Bak Kut Teh",
    "address": "90 Tanjong Pagar Road, 088511",
    "zip": 88511,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/xin-mei-le-bak-kut-teh-1",
    "phone": 62263290,
    "price": 10,
    "cuisine": "Singaporean",
    "halal": false,
    "veg": false
  },
  {
    "name": "The Blue Ginger Restaurant",
    "address": "97 Tanjong Pagar Road, 088518",
    "zip": 88518,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/the-blue-ginger-restaurant",
    "phone": 62223928,
    "price": 30,
    "cuisine": "Peranakan",
    "halal": false,
    "veg": false
  },
  {
    "name": "Hanare",
    "address": "99B Tanjong Pagar Road, 088520",
    "zip": 88520,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/hanare-japanese-cafe-and-restaurant",
    "phone": 62221976,
    "price": 19,
    "cuisine": "Japanese",
    "halal": true,
    "veg": false
  },
  {
    "name": "Tendon Ginza Itsuki",
    "address": "101 TANJONG PAGAR ROAD, 088522",
    "zip": 88522,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/ginza-tendon-itsuki",
    "phone": 62216678,
    "price": 15,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Buttergrill",
    "address": "114 TANJONG PAGAR ROAD, #01-00, 088529",
    "zip": 88529,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/buttergrill",
    "phone": 62212354,
    "price": 45,
    "cuisine": "Western, Italian",
    "halal": false,
    "veg": true
  },
  {
    "name": "Guiga Korean BBQ Restaurant",
    "address": "134, Tanjong Pagar Road, 088538",
    "zip": 88538,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/guiga-korean-bq-134-tanjong-pagar-road",
    "phone": 62213001,
    "price": 30,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Element Restaurant",
    "address": "Amara Hotel, 165 Tanjong Pagar Road, 088539",
    "zip": 88539,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/element-restaurant-amara-hotel",
    "phone": 68792607,
    "price": 39,
    "cuisine": "Fusion, International",
    "halal": false,
    "veg": true
  },
  {
    "name": "Bar-Roque Grill",
    "address": "#01-00, Amara Hotel, 165 Tanjong Pagar Road, 088539",
    "zip": 88539,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/barroque-grill",
    "phone": 64449672,
    "price": 45,
    "cuisine": "French, Western",
    "halal": false,
    "veg": true
  },
  {
    "name": "Shun Ka Shuu Tou",
    "address": "2F, Amara Hotel, 165 Tanjong Pagar Road, 088539",
    "zip": 88539,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/shun-ka-shu-tou",
    "phone": 64447735,
    "price": 30,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Silk Road Restaurant",
    "address": "#02-00, Amara Singapore Hotel, 165 Tanjong Pagar Road, 088539",
    "zip": 88539,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/silk-road",
    "phone": 68792655,
    "price": 41,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Hyangtogol Korean Restaurant",
    "address": "#02-00, Amara Hotel, 165 Tanjong Pagar Road, 088539",
    "zip": 88539,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/hyanggogol-korean-restaurant",
    "phone": 66816423,
    "price": 45,
    "cuisine": "Korean",
    "halal": true,
    "veg": false
  },
  {
    "name": "Thanying Restaurant",
    "address": "#02-00, Amara Hotel, 165 Tanjong Pagar Road, 088539",
    "zip": 88539,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/thanying_restaurant_amara_singapore/",
    "phone": 62224688,
    "price": 45,
    "cuisine": "Thai",
    "halal": false,
    "veg": true
  },
  {
    "name": "Cafe Oriental Amara Hotel",
    "address": "165 Tanjong Pagar Rd, 088539",
    "zip": 88539,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/cafe-oriental",
    "phone": 63226363,
    "price": 23,
    "cuisine": "Singaporean, Malay",
    "halal": false,
    "veg": false
  },
  {
    "name": "Manbok Chinatown Korean BBQ & Steamboat Buffet Restaurant",
    "address": "63 Tanjong Pagar Rd, Singapore 088484",
    "zip": 88484,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/manbok-bbq-buffet",
    "phone": 62219942,
    "price": 30,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Manbok Korean Sea Food Restaurant",
    "address": "58 Tanjong Pagar Rd, Singapore 088479",
    "zip": 88479,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/manbok-bbq-buffet",
    "phone": "6224 6061",
    "price": 30,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Jing Hua Restaurant",
    "address": "21/23 Neil Road, 088815",
    "zip": 88815,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/jing-hua-restaurant-cantonment-tanjong-pagar-chinatown/",
    "phone": 62213060,
    "price": 15,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Akbar 24 hours Restaurant",
    "address": "2 Lim Teck Kim, 088933",
    "zip": 88933,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/akhbar-24",
    "phone": 63242559,
    "price": 15,
    "cuisine": "Malaysian",
    "halal": true,
    "veg": true
  },
  {
    "name": "Outram Ya Hua Rou Gu Cha Restaurant",
    "address": "#01-05/07, Tanjong Pagar Complex, 7 Keppel Road, 089053",
    "zip": 89053,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/outram_park_ya_hua_rou_gu_cha/",
    "phone": 62229610,
    "price": 12,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "First 25 Cafe",
    "address": "7 Hoe Chiang Rd, 089313",
    "zip": 89313,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/first-25-cafe-7-hoe-chiang-road",
    "phone": 62212565,
    "price": 30,
    "cuisine": "Fusion, Italian",
    "halal": false,
    "veg": true
  },
  {
    "name": "Kiku",
    "address": "21 Duxton Road, 089487",
    "zip": 89487,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/kappo-kiku",
    "phone": "�62255567",
    "price": 45,
    "cuisine": "Fusion, Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Pince & Pints",
    "address": "33 Duxton Road, 089497",
    "zip": 89497,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/pince-pints",
    "phone": 62257558,
    "price": 45,
    "cuisine": "American, Western",
    "halal": true,
    "veg": false
  },
  {
    "name": "Etna Italian Restaurant",
    "address": "49/50 Duxton Road, 089513",
    "zip": 89513,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/Etna_Italian_Restaurant___Pizzeria__Duxton_/",
    "phone": 62205513,
    "price": 30,
    "cuisine": "Italian, Western",
    "halal": false,
    "veg": true
  },
  {
    "name": "Rhubarb Le Restaurant",
    "address": "3 Duxton Hill, 089589",
    "zip": 89589,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/rhubarb-le-restaurant",
    "phone": 81275001,
    "price": 45,
    "cuisine": "French, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Sabio Tapas Bar & Restaurant",
    "address": "5 Duxton Hill, 089591",
    "zip": 89591,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/sabio-tapas-bar",
    "phone": 66907562,
    "price": 45,
    "cuisine": "Mediterranean, Spanish, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Buyan Russian Restaurant & Caviar Bar",
    "address": "9/10 Duxton Hill, 089594",
    "zip": 89594,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/buyan-russian-haute-cuisine-caviar-bar",
    "phone": 62237008,
    "price": 30,
    "cuisine": "Russian, Western",
    "halal": true,
    "veg": true
  },
  {
    "name": "Alba 1836",
    "address": "#01-01, 28 Duxton Hill, 089610",
    "zip": 89610,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/alba-1836-singapore",
    "phone": 62222048,
    "price": 45,
    "cuisine": "Italian, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Miz Japanese Restaurant",
    "address": "7 Craig Road, 089667",
    "zip": 89667,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/miz-japanese-restaurant",
    "phone": 62255761,
    "price": 30,
    "cuisine": "Japanese",
    "halal": false,
    "veg": true
  },
  {
    "name": "Pasta Brava Restaurant",
    "address": "11 Craig Road, 089671",
    "zip": 89671,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/pasta-brava",
    "phone": 62277550,
    "price": 45,
    "cuisine": "Italian, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Straits Chinese Nonya Restaurant",
    "address": "#01-08, Chinatown Plaza, 34 Craig Road, 089673",
    "zip": 89673,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/straits-chinese-nonya-restaurant",
    "phone": 65347328,
    "price": 24,
    "cuisine": "Chinese, Peranakan",
    "halal": false,
    "veg": false
  },
  {
    "name": "in ITALY",
    "address": "38 CRAIG ROAD, 089676",
    "zip": 89676,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/initaly-bar-ristorante",
    "phone": 64230918,
    "price": 28,
    "cuisine": "Western, Italian",
    "halal": false,
    "veg": true
  },
  {
    "name": "Binomio",
    "address": "20 CRAIG ROAD, #01-02 CRAIG PLACE, 089692",
    "zip": 89692,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/binomio-spanish-restaurante",
    "phone": 65570547,
    "price": 45,
    "cuisine": "Spanish",
    "halal": false,
    "veg": true
  },
  {
    "name": "PerBacco",
    "address": "20 CRAIG ROAD, #01-03 CRAIG PLACE, 089692",
    "zip": 89692,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/perbacco",
    "phone": 66357130,
    "price": 25,
    "cuisine": "Western, Italian",
    "halal": false,
    "veg": true
  },
  {
    "name": "Mariners' Corner Restaurant",
    "address": "#01-02, Maritime House, 120 Cantonment Road, 089760",
    "zip": 89760,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/mariners-corner-restaurant",
    "phone": 62249928,
    "price": 25,
    "cuisine": "Western",
    "halal": true,
    "veg": true
  },
  {
    "name": "Buffet City",
    "address": "#01-04, Tanjong Pagar Community Centre, 101 Cantonment Road, 089774",
    "zip": 89774,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/buffet-city-singapore",
    "phone": 64109084,
    "price": 27,
    "cuisine": "Fusion, Japanese, Thai",
    "halal": true,
    "veg": false
  },
  {
    "name": "Pho Stop",
    "address": "72 Tanjong Pagar Rd, 088493",
    "zip": 88493,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/pho-stop",
    "phone": "6534 8178",
    "price": 15,
    "cuisine": "Vietnamese",
    "halal": false,
    "veg": true
  },
  {
    "name": "Kko Kko Nara",
    "address": "68 Tanjong Pagar Road, 088489",
    "zip": 88489,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/kko-kko-nara-korean-fried-chicken",
    "phone": "6225 9282",
    "price": 41,
    "cuisine": "Asian,�Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Yan Hong Kee Restaurant�",
    "address": "72 Tanjong Pagar Road, 088493",
    "zip": 88493,
    "cleanliness_grade": "B",
    "website": "http://www.yelu.sg/company/194014/yan-hong-kee-restaurant",
    "phone": 62235275,
    "price": 15,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "The Da Bang",
    "address": "52�Tanjong Pagar Road, 088473",
    "zip": 88473,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/da-bang",
    "phone": "6221 2007",
    "price": 14,
    "cuisine": "Australian",
    "halal": false,
    "veg": false
  },
  {
    "name": "Korean Grill BBQ Buffet",
    "address": "#01-01, 44/45/46�Tanjong Pagar Road, 088465",
    "zip": 88465,
    "cleanliness_grade": "A",
    "website": "http://www.hungrygowhere.com/singapore/Ssikkek_Korean_Grill_BBQ__Tanjong_Pagar_/",
    "phone": 62207119,
    "price": 24,
    "cuisine": "Asian,�Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Xing Xing Korean Restaurant�",
    "address": "28 Tg Pagar Rd, 088451",
    "zip": 88451,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/28-tanjong-pagar-road-singapore-088451",
    "phone": 0,
    "price": 25,
    "cuisine": "Asian,�Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Old House",
    "address": "25 Neil Rd, 088816",
    "zip": 88816,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/old-house",
    "phone": 62231633,
    "price": 15,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Herbal Oasis",
    "address": "27A Neil Road, 088817",
    "zip": 88817,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/herbal-oasis",
    "phone": 62218798,
    "price": 10,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Straits Chinese Restaurant",
    "address": "34 Craig Road, #01-08 Chinatown Plaza, 089673",
    "zip": 89673,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/straits-chinese-nonya-restaurant",
    "phone": 65347328,
    "price": 24,
    "cuisine": "Asian,�Chinese,�Peranakan",
    "halal": false,
    "veg": false
  },
  {
    "name": "Chang Soon Charcoal Hk Roasted",
    "address": "120 Neil Rd, 088855",
    "zip": 88855,
    "cleanliness_grade": "B",
    "website": "https://foursquare.com/v/??-chang-shun-charcoal-hong-kong-style-roasted/4c96ff2303413704f33089ef",
    "phone": 83228597,
    "price": 20,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "MEAT liquor Singapore",
    "address": "99 Duxton Rd, 089543",
    "zip": 89543,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/meatliquor-sin",
    "phone": 62215343,
    "price": 30,
    "cuisine": "International",
    "halal": false,
    "veg": false
  },
  {
    "name": "Bi Won Korean Restaurants & Pub",
    "address": "Tanjong Pagar Shop Houses, 9 Duxton Hill, 089593",
    "zip": 89593,
    "cleanliness_grade": "B",
    "website": "http://www.hungrygowhere.com/singapore/bi_won_korean_restaurants_pub/",
    "phone": 62251141,
    "price": 17,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "L'Entrecote",
    "address": "36 Duxton Hill, 089614",
    "zip": 89614,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/lentrecote-4",
    "phone": 66907561,
    "price": 38,
    "cuisine": "International",
    "halal": false,
    "veg": false
  },
  {
    "name": "Twins Korean Restaurant",
    "address": "7 Craig Rd, 089667",
    "zip": 89667,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/twins",
    "phone": 62215205,
    "price": 26,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "U2 Kitchen",
    "address": "2 Craig Rd, Singapore 089662",
    "zip": 89662,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/u2-kitchen",
    "phone": 63278829,
    "price": 10,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Sicilia Mia",
    "address": "75 Duxton Rd, 089534",
    "zip": 89534,
    "cleanliness_grade": "A",
    "website": "http://www.sicilia-mia.com/cuisine.php",
    "phone": 62263351,
    "price": 18,
    "cuisine": "Italian",
    "halal": false,
    "veg": false
  },
  {
    "name": "Ken Japanish Restaurant",
    "address": "70 Duxton Rd, Singapore 089529",
    "zip": 89529,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/ken-japanese-cuisine",
    "phone": 62214885,
    "price": 25,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Sprout- Salad Bar",
    "address": "41 Duxton Rd, 089505",
    "zip": 89505,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/sprout-salad-bar",
    "phone": 62211227,
    "price": 20,
    "cuisine": "Salad",
    "halal": false,
    "veg": true
  },
  {
    "name": "One Fork Two Stick Kitchen",
    "address": "89 Tg Pagar Rd, 088510",
    "zip": 88510,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/one-fork-two-stick-kitchen",
    "phone": 0,
    "price": 26,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Kanda Wadatsumi",
    "address": "50 Tras Street, 078989",
    "zip": 78989,
    "cleanliness_grade": "A",
    "website": "http://www.kanda-wadatsumi.sg/en/",
    "phone": 62216264,
    "price": 32,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Conclave",
    "address": "40 Tras St, 078979",
    "zip": 78979,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/conclave",
    "phone": 62211486,
    "price": 20,
    "cuisine": "International",
    "halal": false,
    "veg": false
  },
  {
    "name": "Todamgol",
    "address": "31 Tanjong Pagar Rd, Singapore 088454",
    "zip": 88454,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/todamgol-korean-restaurant",
    "phone": 62247077,
    "price": 35,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  },
  {
    "name": "Caf� & Bar Gavroche",
    "address": "69 Tras St, 079008",
    "zip": 79008,
    "cleanliness_grade": "A",
    "website": "http://www.burpple.com/cafe-gavroche",
    "phone": 62254869,
    "price": 28,
    "cuisine": "French, Western",
    "halal": false,
    "veg": false
  },
  {
    "name": "Hwang Sil Korean Chinese Restaurant",
    "address": "069116, 38 Maxwell Rd, 069116",
    "zip": 69116,
    "cleanliness_grade": "B",
    "website": "https://www.facebook.com/hwangsilkorean/",
    "phone": 62244371,
    "price": 15,
    "cuisine": "Korean, Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Clay Abode",
    "address": "32 Maxwell Rd, Singapore 069115",
    "zip": 69115,
    "cleanliness_grade": "B",
    "website": "http://www.burpple.com/clay-abode",
    "phone": 62276137,
    "price": 15,
    "cuisine": "Chinese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Ichidon",
    "address": "32 Maxwell Rd, 069115",
    "zip": 69115,
    "cleanliness_grade": "B",
    "website": "http://www.hungrygowhere.com/singapore/ichidon_restaurant_formerly_six_restaurants/",
    "phone": 65348189,
    "price": 45,
    "cuisine": "Japanese",
    "halal": false,
    "veg": false
  },
  {
    "name": "Eee Mo BBQ",
    "address": "32 Maxwell Rd, 069115",
    "zip": 69115,
    "cleanliness_grade": "A",
    "website": "https://www.facebook.com/www.Eeemobbq.co.kr/",
    "phone": 65094173,
    "price": 25,
    "cuisine": "Korean",
    "halal": false,
    "veg": false
  }
]

module.exports = allRestaurants; 