var dummyUsers = [
  {
    "name": "Evangeline",
    "password": 393,
    "title": "Support Staff",
    "picture": "URL",
    "email": "arcu@ornare.org",
    "phone": "(02) 3212 4733",
    "tagline": "Duis elementum, dui quis accumsan convallis, ante lectus",
    "available": "Monday",
    "nationality": "American",
    "cuisine": 0
  },
  {
    "name": "Germaine",
    "password": 483,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "pharetra.ut.pharetra@mauriseu.org",
    "phone": "(01) 4098 7121",
    "tagline": "diam lorem, auctor quis, tristique ac, eleifend",
    "available": 0,
    "nationality": "Malaysian",
    "cuisine": "Chinese ,  Korean ,  Thai,  French ,  Western"
  },
  {
    "name": "Ashton",
    "password": 621,
    "title": "HR",
    "picture": "URL",
    "email": "in.dolor@dictumultricies.org",
    "phone": "(01) 7675 4365",
    "tagline": "rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam",
    "available": "Thursday ,  Wednesday , Monday ,  Tuesday",
    "nationality": "European",
    "cuisine": "Thai,  Western"
  },
  {
    "name": "Xenos",
    "password": 895,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "Curabitur.massa@nonummyultricies.edu",
    "phone": "(03) 0606 0921",
    "tagline": "tellus sem mollis dui, in sodales",
    "available": "Tuesday ,  Friday,  Thursday",
    "nationality": "Malaysian",
    "cuisine": "Chinese ,  Thai,  Korean , Indian ,  French ,  Western ,  Vietnamese"
  },
  {
    "name": "Colt",
    "password": 669,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "sit.amet.risus@cursusNunc.ca",
    "phone": "(06) 8587 9138",
    "tagline": "nisi nibh lacinia orci,",
    "available": 0,
    "nationality": "American",
    "cuisine": 0
  },
  {
    "name": "Yvonne",
    "password": 531,
    "title": "Support Staff",
    "picture": "URL",
    "email": "dictum.eu@scelerisque.co.uk",
    "phone": "(02) 1484 3151",
    "tagline": "tellus justo sit amet nulla. Donec non justo. Proin non",
    "available": "Wednesday ,  Friday,  Thursday ,  Tuesday , Monday",
    "nationality": "European",
    "cuisine": "French ,  Vietnamese ,  Chinese ,  Thai,  Western , Indian"
  },
  {
    "name": "Demetrius",
    "password": 871,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "tellus.eu@Crasvulputatevelit.org",
    "phone": "(04) 9268 9405",
    "tagline": "Morbi metus.",
    "available": "Tuesday ,  Thursday , Monday",
    "nationality": "European",
    "cuisine": "Chinese"
  },
  {
    "name": "Shelly",
    "password": 132,
    "title": "HR",
    "picture": "URL",
    "email": "Curae@eget.co.uk",
    "phone": "(09) 8471 5879",
    "tagline": "laoreet, libero",
    "available": "Friday",
    "nationality": "Chinese",
    "cuisine": "Thai"
  },
  {
    "name": "Colton",
    "password": 534,
    "title": "HR",
    "picture": "URL",
    "email": "tristique.ac@nec.org",
    "phone": "(09) 1955 6803",
    "tagline": "non, lobortis quis, pede. Suspendisse dui.",
    "available": 0,
    "nationality": "Australian",
    "cuisine": "Chinese"
  },
  {
    "name": "Jennifer",
    "password": 112,
    "title": "Support Staff",
    "picture": "URL",
    "email": "vehicula.Pellentesque.tincidunt@dis.ca",
    "phone": "(05) 1820 9291",
    "tagline": "Ut",
    "available": "Monday ,  Wednesday ,  Friday,  Tuesday ,  Thursday",
    "nationality": "European",
    "cuisine": "Korean ,  Western ,  French"
  },
  {
    "name": "Salvador",
    "password": 942,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "consequat@natoque.edu",
    "phone": "(07) 6125 9880",
    "tagline": "eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus",
    "available": "Friday, Monday ,  Wednesday",
    "nationality": "Chinese",
    "cuisine": "Korean ,  Vietnamese ,  Western ,  Chinese , Indian"
  },
  {
    "name": "Penelope",
    "password": 693,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "egestas@acfeugiat.ca",
    "phone": "(04) 2847 6321",
    "tagline": "nec, euismod in, dolor. Fusce feugiat. Lorem",
    "available": "Wednesday , Monday ,  Friday",
    "nationality": "Indian",
    "cuisine": "Thai,  French ,  Korean ,  Vietnamese ,  Western , Indian"
  },
  {
    "name": "Ayanna",
    "password": 622,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "neque.Nullam.nisl@enim.edu",
    "phone": "(06) 9211 7723",
    "tagline": "leo. Morbi neque tellus,",
    "available": 0,
    "nationality": "American",
    "cuisine": 0
  },
  {
    "name": "Jarrod",
    "password": 964,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "at.lacus@velvulputateeu.ca",
    "phone": "(08) 3109 9217",
    "tagline": "eros. Nam consequat dolor vitae dolor.",
    "available": "Wednesday ,  Friday,  Thursday ,  Tuesday , Monday",
    "nationality": "Australian",
    "cuisine": "French , Indian ,  Western ,  Vietnamese"
  },
  {
    "name": "Autumn",
    "password": 601,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "quam.vel@molestiearcuSed.net",
    "phone": "(01) 4181 8829",
    "tagline": "arcu et pede. Nunc sed orci lobortis augue scelerisque",
    "available": 0,
    "nationality": "Malaysian",
    "cuisine": "Korean ,  Vietnamese ,  Chinese ,  Thai, Indian"
  },
  {
    "name": "Illana",
    "password": 161,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "accumsan@Proin.ca",
    "phone": "(06) 8093 9916",
    "tagline": "tellus faucibus leo, in lobortis tellus justo sit",
    "available": "Thursday",
    "nationality": "Chinese",
    "cuisine": "Western ,  French , Indian ,  Vietnamese ,  Thai"
  },
  {
    "name": "Nicholas",
    "password": 621,
    "title": "HR",
    "picture": "URL",
    "email": "lobortis.quam@idante.com",
    "phone": "(09) 6875 3920",
    "tagline": "laoreet",
    "available": "Thursday",
    "nationality": "American",
    "cuisine": "Chinese ,  Western ,  French"
  },
  {
    "name": "Ulla",
    "password": 729,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "non@facilisisnonbibendum.ca",
    "phone": "(03) 6299 2480",
    "tagline": "semper pretium neque.",
    "available": 0,
    "nationality": "Australian",
    "cuisine": "Thai, Indian ,  Vietnamese ,  Korean ,  Western ,  French"
  },
  {
    "name": "Benjamin",
    "password": 435,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "Suspendisse@etmagnis.ca",
    "phone": "(07) 4991 2945",
    "tagline": "ac, fermentum vel,",
    "available": "Wednesday",
    "nationality": "American",
    "cuisine": "Vietnamese ,  Chinese ,  Thai,  French ,  Western ,  Korean"
  },
  {
    "name": "Lamar",
    "password": 186,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "malesuada@scelerisqueduiSuspendisse.net",
    "phone": "(02) 6595 0030",
    "tagline": "imperdiet dictum",
    "available": "Tuesday ,  Friday",
    "nationality": "European",
    "cuisine": "Vietnamese ,  Korean ,  Chinese ,  Thai, Indian ,  French"
  },
  {
    "name": "Amery",
    "password": 363,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "tincidunt@cursusaenim.com",
    "phone": "(06) 1204 4176",
    "tagline": "tempor bibendum. Donec felis orci, adipiscing non, luctus sit",
    "available": "Tuesday ,  Thursday , Monday ,  Friday,  Wednesday",
    "nationality": "Indian",
    "cuisine": "Chinese ,  Western , Indian ,  French ,  Korean"
  },
  {
    "name": "Kay",
    "password": 599,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "mattis.velit@vehiculaaliquet.net",
    "phone": "(08) 6275 4432",
    "tagline": "quis diam luctus lobortis. Class aptent taciti sociosqu ad",
    "available": "Tuesday ,  Thursday , Monday ,  Friday,  Wednesday",
    "nationality": "Chinese",
    "cuisine": "Vietnamese , Indian ,  Thai,  Western ,  French"
  },
  {
    "name": "Pearl",
    "password": 805,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "sit.amet@lobortis.ca",
    "phone": "(06) 4973 5152",
    "tagline": "Nulla tempor augue ac ipsum. Phasellus",
    "available": "Friday, Monday ,  Thursday ,  Tuesday",
    "nationality": "Australian",
    "cuisine": "Thai,  Western ,  Korean ,  French ,  Chinese"
  },
  {
    "name": "Sydnee",
    "password": 268,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "semper@Nunc.co.uk",
    "phone": "(04) 3183 0479",
    "tagline": "Nunc ac sem",
    "available": "Monday ,  Tuesday ,  Wednesday ,  Friday,  Thursday",
    "nationality": "Malaysian",
    "cuisine": "Chinese ,  Korean ,  Thai"
  },
  {
    "name": "Kelly",
    "password": 656,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "lorem.sit@rutrum.net",
    "phone": "(06) 7649 5851",
    "tagline": "Proin velit. Sed malesuada",
    "available": "Thursday , Monday ,  Friday,  Wednesday ,  Tuesday",
    "nationality": "European",
    "cuisine": "Vietnamese ,  Thai, Indian ,  Chinese ,  Korean ,  French"
  },
  {
    "name": "Keith",
    "password": 731,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "a.auctor.non@dolordolortempus.ca",
    "phone": "(05) 0991 1404",
    "tagline": "Nunc ullamcorper, velit in",
    "available": "Thursday ,  Tuesday , Monday",
    "nationality": "American",
    "cuisine": "Chinese ,  French , Indian ,  Korean ,  Western ,  Vietnamese ,  Thai"
  },
  {
    "name": "Vivien",
    "password": 362,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "porta.elit@ametdapibusid.ca",
    "phone": "(05) 9617 9178",
    "tagline": "Nulla facilisi. Sed neque. Sed",
    "available": "Friday,  Thursday ,  Wednesday ,  Tuesday",
    "nationality": "Australian",
    "cuisine": "Western ,  Thai,  Vietnamese ,  French , Indian"
  },
  {
    "name": "Jackson",
    "password": 683,
    "title": "HR",
    "picture": "URL",
    "email": "tristique.senectus@ullamcorperDuis.co.uk",
    "phone": "(02) 8541 5315",
    "tagline": "dictum eleifend, nunc risus varius",
    "available": "Thursday , Monday",
    "nationality": "Chinese",
    "cuisine": "Indian ,  Western ,  Korean ,  Thai,  Vietnamese ,  Chinese ,  French"
  },
  {
    "name": "Yoko",
    "password": 547,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "vitae.velit.egestas@imperdietnon.com",
    "phone": "(04) 8182 0567",
    "tagline": "consequat, lectus sit amet luctus",
    "available": "Wednesday , Monday ,  Thursday",
    "nationality": "Chinese",
    "cuisine": "Vietnamese , Indian ,  Chinese"
  },
  {
    "name": "Fredericka",
    "password": 361,
    "title": "HR",
    "picture": "URL",
    "email": "et.ultrices@acturpisegestas.ca",
    "phone": "(01) 6138 4269",
    "tagline": "pede. Cras vulputate",
    "available": "Friday, Monday ,  Tuesday ,  Wednesday ,  Thursday",
    "nationality": "Malaysian",
    "cuisine": "Indian ,  French ,  Thai"
  },
  {
    "name": "Donovan",
    "password": 561,
    "title": "Support Staff",
    "picture": "URL",
    "email": "lorem.ac@quis.co.uk",
    "phone": "(03) 5783 6852",
    "tagline": "mus. Aenean eget magna. Suspendisse",
    "available": "Wednesday ,  Friday,  Tuesday , Monday ,  Thursday",
    "nationality": "Indian",
    "cuisine": "Chinese ,  Vietnamese ,  French ,  Western"
  },
  {
    "name": "Murphy",
    "password": 192,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "quis@Pellentesquehabitantmorbi.ca",
    "phone": "(01) 8901 5762",
    "tagline": "nec",
    "available": "Wednesday ,  Thursday , Monday",
    "nationality": "Malaysian",
    "cuisine": "Korean ,  Thai,  Chinese ,  French ,  Western , Indian"
  },
  {
    "name": "Eugenia",
    "password": 410,
    "title": "HR",
    "picture": "URL",
    "email": "dui@purusMaecenaslibero.edu",
    "phone": "(01) 1698 2610",
    "tagline": "molestie arcu. Sed eu nibh vulputate",
    "available": "Thursday",
    "nationality": "Malaysian",
    "cuisine": "Indian ,  Thai"
  },
  {
    "name": "Wynter",
    "password": 715,
    "title": "HR",
    "picture": "URL",
    "email": "Suspendisse.sed.dolor@famesacturpis.ca",
    "phone": "(06) 2867 1479",
    "tagline": "pharetra nibh. Aliquam ornare,",
    "available": "Wednesday ,  Thursday , Monday ,  Tuesday",
    "nationality": "Malaysian",
    "cuisine": "Korean ,  French"
  },
  {
    "name": "Quinn",
    "password": 324,
    "title": "HR",
    "picture": "URL",
    "email": "Cum@laoreetlibero.edu",
    "phone": "(07) 6019 8660",
    "tagline": "orci. Ut sagittis",
    "available": "Wednesday , Monday",
    "nationality": "European",
    "cuisine": 0
  },
  {
    "name": "Shelley",
    "password": 414,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "non@dictumplacerat.ca",
    "phone": "(07) 9461 8659",
    "tagline": "lorem ipsum",
    "available": "Tuesday ,  Friday",
    "nationality": "Indian",
    "cuisine": "Thai,  Korean ,  Western ,  French ,  Chinese"
  },
  {
    "name": "Wesley",
    "password": 405,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "pede@egetnisi.org",
    "phone": "(02) 3210 3954",
    "tagline": "tempor arcu. Vestibulum ut eros",
    "available": "Wednesday ,  Friday,  Thursday , Monday",
    "nationality": "Australian",
    "cuisine": "Vietnamese ,  Thai"
  },
  {
    "name": "Edward",
    "password": 171,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "ipsum@rutrum.edu",
    "phone": "(08) 7928 6822",
    "tagline": "sapien. Aenean",
    "available": "Tuesday , Monday ,  Thursday",
    "nationality": "American",
    "cuisine": "Vietnamese , Indian ,  Chinese ,  Thai,  French"
  },
  {
    "name": "Candice",
    "password": 373,
    "title": "Support Staff",
    "picture": "URL",
    "email": "ac.tellus@viverraMaecenasiaculis.ca",
    "phone": "(07) 6419 2706",
    "tagline": "posuere at,",
    "available": "Wednesday",
    "nationality": "Chinese",
    "cuisine": "Vietnamese ,  Thai,  Chinese"
  },
  {
    "name": "Cailin",
    "password": 639,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "leo.in.lobortis@arcuVivamussit.com",
    "phone": "(03) 5248 2961",
    "tagline": "vel lectus. Cum",
    "available": "Friday",
    "nationality": "Australian",
    "cuisine": "Western ,  Chinese ,  French ,  Thai"
  },
  {
    "name": "Bryar",
    "password": 794,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "venenatis.lacus.Etiam@ipsumleoelementum.ca",
    "phone": "(06) 3736 9611",
    "tagline": "nec mauris blandit mattis.",
    "available": "Tuesday , Monday ,  Friday,  Wednesday",
    "nationality": "Chinese",
    "cuisine": "French ,  Thai,  Chinese"
  },
  {
    "name": "Amal",
    "password": 924,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "Cum.sociis.natoque@urna.co.uk",
    "phone": "(07) 5800 4210",
    "tagline": "enim. Nunc ut erat. Sed nunc est, mollis non,",
    "available": "Wednesday ,  Thursday ,  Tuesday , Monday ,  Friday",
    "nationality": "European",
    "cuisine": "Western ,  Chinese , Indian ,  Vietnamese"
  },
  {
    "name": "Maya",
    "password": 644,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "et.nunc.Quisque@idnunc.com",
    "phone": "(02) 6760 1526",
    "tagline": "convallis in, cursus",
    "available": "Tuesday ,  Wednesday",
    "nationality": "Indian",
    "cuisine": "Thai,  Western , Indian ,  Chinese ,  Vietnamese"
  },
  {
    "name": "Keely",
    "password": 699,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "ligula@Aliquamauctorvelit.edu",
    "phone": "(09) 3964 9300",
    "tagline": "ultrices. Duis volutpat nunc sit amet",
    "available": "Monday ,  Thursday ,  Friday",
    "nationality": "Chinese",
    "cuisine": "Western ,  Vietnamese"
  },
  {
    "name": "Molly",
    "password": 359,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "mauris@pede.net",
    "phone": "(01) 5725 1571",
    "tagline": "vulputate mauris sagittis placerat. Cras dictum ultricies ligula.",
    "available": "Monday ,  Wednesday ,  Thursday ,  Friday",
    "nationality": "European",
    "cuisine": "Indian ,  French ,  Vietnamese ,  Chinese ,  Thai"
  },
  {
    "name": "Mona",
    "password": 260,
    "title": "HR",
    "picture": "URL",
    "email": "ultrices@arcuvelquam.org",
    "phone": "(07) 4642 3663",
    "tagline": "urna",
    "available": "Tuesday , Monday ,  Thursday",
    "nationality": "European",
    "cuisine": "Indian ,  French ,  Chinese"
  },
  {
    "name": "Rylee",
    "password": 279,
    "title": "HR",
    "picture": "URL",
    "email": "blandit@egestasrhoncusProin.net",
    "phone": "(02) 6460 7483",
    "tagline": "nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam",
    "available": "Tuesday ,  Wednesday",
    "nationality": "European",
    "cuisine": "Chinese ,  Korean ,  Thai,  Western"
  },
  {
    "name": "Hyacinth",
    "password": 313,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "lectus.pede@consectetueradipiscingelit.edu",
    "phone": "(09) 0392 0592",
    "tagline": "orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus",
    "available": "Thursday ,  Friday, Monday",
    "nationality": "Malaysian",
    "cuisine": "Chinese , Indian ,  Korean ,  French ,  Vietnamese ,  Western"
  },
  {
    "name": "Thor",
    "password": 823,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "vulputate@nulla.org",
    "phone": "(05) 3877 1883",
    "tagline": "volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam",
    "available": 0,
    "nationality": "Chinese",
    "cuisine": "Indian ,  Chinese ,  Korean ,  Western ,  Vietnamese ,  Thai,  French"
  },
  {
    "name": "Brent",
    "password": 850,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "neque@odiotristique.net",
    "phone": "(09) 9213 9298",
    "tagline": "Phasellus nulla.",
    "available": 0,
    "nationality": "Chinese",
    "cuisine": "Vietnamese ,  French ,  Western ,  Chinese ,  Thai,  Korean , Indian"
  },
  {
    "name": "Hedy",
    "password": 828,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "nascetur@est.edu",
    "phone": "(04) 5874 8366",
    "tagline": "Curabitur",
    "available": 0,
    "nationality": "American",
    "cuisine": "French ,  Vietnamese , Indian ,  Thai,  Korean ,  Chinese ,  Western"
  },
  {
    "name": "Rhea",
    "password": 511,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "et@sem.com",
    "phone": "(04) 8250 2138",
    "tagline": "eu, euismod ac,",
    "available": "Tuesday ,  Wednesday , Monday ,  Friday",
    "nationality": "Chinese",
    "cuisine": "Vietnamese , Indian ,  Western"
  },
  {
    "name": "Elliott",
    "password": 725,
    "title": "Support Staff",
    "picture": "URL",
    "email": "Proin@Cras.ca",
    "phone": "(01) 1192 4034",
    "tagline": "nonummy ac, feugiat non,",
    "available": "Thursday",
    "nationality": "Malaysian",
    "cuisine": "Indian"
  },
  {
    "name": "Britanney",
    "password": 257,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "velit.in.aliquet@Mauris.net",
    "phone": "(01) 8803 3650",
    "tagline": "arcu. Aliquam ultrices iaculis odio. Nam interdum enim",
    "available": "Monday ,  Friday,  Thursday ,  Wednesday ,  Tuesday",
    "nationality": "European",
    "cuisine": "Western , Indian ,  Vietnamese ,  Chinese ,  French ,  Thai"
  },
  {
    "name": "Aidan",
    "password": 703,
    "title": "HR",
    "picture": "URL",
    "email": "ridiculus.mus.Proin@aliquamiaculislacus.ca",
    "phone": "(04) 0579 9117",
    "tagline": "nec, imperdiet nec, leo. Morbi",
    "available": "Tuesday , Monday ,  Friday",
    "nationality": "American",
    "cuisine": "Thai, Indian ,  Vietnamese ,  French"
  },
  {
    "name": "Aladdin",
    "password": 992,
    "title": "HR",
    "picture": "URL",
    "email": "Proin.ultrices@id.net",
    "phone": "(07) 7655 2259",
    "tagline": "sed dictum eleifend, nunc risus varius orci, in",
    "available": "Tuesday , Monday ,  Wednesday ,  Thursday ,  Friday",
    "nationality": "Malaysian",
    "cuisine": "Korean , Indian ,  French ,  Vietnamese ,  Chinese ,  Western"
  },
  {
    "name": "Maisie",
    "password": 948,
    "title": "HR",
    "picture": "URL",
    "email": "dolor.sit@semperrutrumFusce.net",
    "phone": "(04) 6232 4008",
    "tagline": "aliquam eros turpis non enim.",
    "available": "Wednesday ,  Tuesday ,  Thursday , Monday ,  Friday",
    "nationality": "Indian",
    "cuisine": "Western , Indian ,  Korean"
  },
  {
    "name": "Upton",
    "password": 961,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "Cum.sociis@congueelit.org",
    "phone": "(08) 1607 0076",
    "tagline": "quis massa. Mauris vestibulum,",
    "available": "Wednesday ,  Thursday",
    "nationality": "Indian",
    "cuisine": "Chinese ,  Vietnamese ,  French , Indian ,  Korean ,  Western"
  },
  {
    "name": "Daniel",
    "password": 944,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "et.rutrum@odiotristique.org",
    "phone": "(08) 9822 0763",
    "tagline": "eu dui. Cum",
    "available": "Thursday , Monday ,  Wednesday ,  Tuesday ,  Friday",
    "nationality": "Australian",
    "cuisine": "Chinese ,  Vietnamese"
  },
  {
    "name": "Rooney",
    "password": 372,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "amet@rutrum.com",
    "phone": "(01) 8907 2370",
    "tagline": "aliquet molestie tellus. Aenean egestas hendrerit",
    "available": "Wednesday",
    "nationality": "Chinese",
    "cuisine": "Vietnamese , Indian ,  Chinese ,  Thai,  Western"
  },
  {
    "name": "Wyatt",
    "password": 944,
    "title": "HR",
    "picture": "URL",
    "email": "Duis.a.mi@Phasellusin.edu",
    "phone": "(04) 6908 2933",
    "tagline": "nisi dictum augue malesuada malesuada. Integer",
    "available": "Thursday , Monday ,  Tuesday",
    "nationality": "Australian",
    "cuisine": "Vietnamese , Indian"
  },
  {
    "name": "Aubrey",
    "password": 426,
    "title": "HR",
    "picture": "URL",
    "email": "imperdiet@sedsapien.edu",
    "phone": "(01) 1938 4999",
    "tagline": "montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque",
    "available": "Friday",
    "nationality": "Malaysian",
    "cuisine": 0
  },
  {
    "name": "Abel",
    "password": 635,
    "title": "HR",
    "picture": "URL",
    "email": "arcu@mauriseu.ca",
    "phone": "(01) 9177 5175",
    "tagline": "placerat, augue. Sed",
    "available": "Wednesday ,  Thursday , Monday",
    "nationality": "American",
    "cuisine": "Thai,  Korean ,  French , Indian ,  Chinese ,  Western"
  },
  {
    "name": "Liberty",
    "password": 811,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "turpis.egestas.Aliquam@magnatellus.edu",
    "phone": "(06) 5828 0185",
    "tagline": "interdum feugiat. Sed nec metus",
    "available": "Wednesday ,  Tuesday , Monday",
    "nationality": "Chinese",
    "cuisine": "Thai,  Western ,  Chinese , Indian ,  French ,  Korean"
  },
  {
    "name": "Lisandra",
    "password": 395,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "lobortis.risus@diam.ca",
    "phone": "(07) 6496 2811",
    "tagline": "lectus rutrum urna, nec luctus felis purus ac tellus.",
    "available": "Friday,  Wednesday , Monday ,  Thursday ,  Tuesday",
    "nationality": "Australian",
    "cuisine": "French"
  },
  {
    "name": "Amethyst",
    "password": 655,
    "title": "Support Staff",
    "picture": "URL",
    "email": "mollis.vitae.posuere@SuspendisseduiFusce.ca",
    "phone": "(03) 8485 3335",
    "tagline": "id magna et ipsum cursus vestibulum. Mauris magna. Duis",
    "available": "Thursday ,  Friday,  Tuesday , Monday",
    "nationality": "Chinese",
    "cuisine": "Vietnamese ,  Western ,  Thai, Indian ,  Korean"
  },
  {
    "name": "Malachi",
    "password": 520,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "cursus.et.magna@cursusaenim.net",
    "phone": "(02) 5298 0649",
    "tagline": "sed orci lobortis augue",
    "available": "Tuesday ,  Thursday",
    "nationality": "Australian",
    "cuisine": "Thai,  French , Indian"
  },
  {
    "name": "Kuame",
    "password": 931,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "nulla.Integer@convalliserateget.org",
    "phone": "(08) 3148 3118",
    "tagline": "vulputate, nisi sem semper erat, in consectetuer ipsum nunc id",
    "available": "Tuesday ,  Thursday ,  Wednesday ,  Friday",
    "nationality": "Chinese",
    "cuisine": "Korean"
  },
  {
    "name": "Buffy",
    "password": 706,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "enim.nec.tempus@orciquis.com",
    "phone": "(07) 8130 2326",
    "tagline": "magna sed dui. Fusce aliquam,",
    "available": "Monday ,  Thursday ,  Tuesday ,  Friday",
    "nationality": "Chinese",
    "cuisine": "Western ,  French , Indian ,  Thai,  Vietnamese"
  },
  {
    "name": "Elijah",
    "password": 278,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "eget@acorci.org",
    "phone": "(08) 0582 1131",
    "tagline": "Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas",
    "available": 0,
    "nationality": "American",
    "cuisine": "Chinese ,  Thai,  Vietnamese"
  },
  {
    "name": "Elijah",
    "password": 991,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "ornare@dignissimpharetra.net",
    "phone": "(09) 5183 8440",
    "tagline": "semper egestas, urna justo faucibus lectus,",
    "available": "Wednesday ,  Thursday",
    "nationality": "Australian",
    "cuisine": "Chinese ,  Vietnamese ,  French ,  Western ,  Korean ,  Thai"
  },
  {
    "name": "Jasper",
    "password": 636,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "placerat@ametmassaQuisque.co.uk",
    "phone": "(02) 4016 9270",
    "tagline": "Proin sed turpis nec mauris blandit mattis. Cras",
    "available": "Monday",
    "nationality": "American",
    "cuisine": "Chinese ,  Western ,  Korean , Indian ,  Vietnamese ,  Thai"
  },
  {
    "name": "Hedda",
    "password": 797,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "consectetuer.adipiscing@ligulaconsectetuerrhoncus.ca",
    "phone": "(03) 3891 5715",
    "tagline": "ultrices. Duis volutpat nunc sit amet metus.",
    "available": 0,
    "nationality": "European",
    "cuisine": 0
  },
  {
    "name": "Mercedes",
    "password": 769,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "augue@nequevitae.edu",
    "phone": "(09) 6603 1031",
    "tagline": "turpis. Aliquam adipiscing",
    "available": "Friday,  Wednesday , Monday ,  Thursday ,  Tuesday",
    "nationality": "Australian",
    "cuisine": "Thai,  Chinese"
  },
  {
    "name": "Merritt",
    "password": 340,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "turpis@ultricesposuere.com",
    "phone": "(05) 1806 8463",
    "tagline": "Fusce aliquet",
    "available": "Thursday ,  Friday, Monday ,  Tuesday",
    "nationality": "European",
    "cuisine": "Western ,  French , Indian ,  Chinese ,  Thai"
  },
  {
    "name": "Timon",
    "password": 147,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "ac.libero.nec@sitamet.co.uk",
    "phone": "(08) 5472 8573",
    "tagline": "eleifend",
    "available": 0,
    "nationality": "European",
    "cuisine": 0
  },
  {
    "name": "Alana",
    "password": 186,
    "title": "Support Staff",
    "picture": "URL",
    "email": "tempor.diam.dictum@pellentesque.edu",
    "phone": "(08) 6674 8387",
    "tagline": "Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem",
    "available": "Thursday , Monday",
    "nationality": "European",
    "cuisine": "French ,  Chinese , Indian ,  Korean ,  Thai,  Western"
  },
  {
    "name": "Keiko",
    "password": 306,
    "title": "HR",
    "picture": "URL",
    "email": "ornare.In.faucibus@Sedid.net",
    "phone": "(08) 2057 6568",
    "tagline": "nibh sit",
    "available": "Wednesday ,  Friday,  Tuesday",
    "nationality": "Chinese",
    "cuisine": "French ,  Western ,  Thai,  Korean , Indian ,  Vietnamese ,  Chinese"
  },
  {
    "name": "Avye",
    "password": 276,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "id@ullamcorperDuis.edu",
    "phone": "(07) 0998 0543",
    "tagline": "nunc sit amet metus. Aliquam erat volutpat. Nulla",
    "available": "Wednesday ,  Tuesday ,  Thursday ,  Friday",
    "nationality": "Malaysian",
    "cuisine": "Indian ,  Western ,  Vietnamese ,  French ,  Chinese ,  Korean ,  Thai"
  },
  {
    "name": "Ethan",
    "password": 411,
    "title": "Support Staff",
    "picture": "URL",
    "email": "egestas@augue.com",
    "phone": "(09) 4841 7395",
    "tagline": "lacus. Quisque",
    "available": "Thursday ,  Friday, Monday ,  Tuesday ,  Wednesday",
    "nationality": "Indian",
    "cuisine": "Chinese ,  Thai, Indian ,  Korean ,  French ,  Vietnamese ,  Western"
  },
  {
    "name": "Nasim",
    "password": 763,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "turpis.vitae.purus@Sed.edu",
    "phone": "(07) 8015 1969",
    "tagline": "Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam",
    "available": 0,
    "nationality": "Australian",
    "cuisine": "Korean ,  Western ,  Vietnamese ,  Chinese , Indian ,  French ,  Thai"
  },
  {
    "name": "Grant",
    "password": 222,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "sapien@In.org",
    "phone": "(02) 2098 2028",
    "tagline": "feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam",
    "available": "Thursday ,  Tuesday",
    "nationality": "Indian",
    "cuisine": "Vietnamese"
  },
  {
    "name": "Noah",
    "password": 300,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "egestas.Aliquam.nec@imperdietullamcorperDuis.net",
    "phone": "(07) 4025 4238",
    "tagline": "magna.",
    "available": "Thursday ,  Friday, Monday ,  Wednesday",
    "nationality": "Chinese",
    "cuisine": "Vietnamese ,  Thai,  Western , Indian ,  Chinese ,  Korean"
  },
  {
    "name": "Kelly",
    "password": 176,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "montes.nascetur@egettinciduntdui.edu",
    "phone": "(09) 6000 8128",
    "tagline": "eu arcu. Morbi sit amet massa.",
    "available": "Thursday ,  Wednesday ,  Friday,  Tuesday , Monday",
    "nationality": "American",
    "cuisine": "Chinese ,  Thai, Indian ,  Western ,  French ,  Vietnamese ,  Korean"
  },
  {
    "name": "Alexander",
    "password": 195,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "vulputate.dui.nec@cursus.com",
    "phone": "(03) 1270 3238",
    "tagline": "Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula.",
    "available": "Friday,  Thursday",
    "nationality": "Indian",
    "cuisine": "Chinese"
  },
  {
    "name": "MacKensie",
    "password": 440,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "Nullam.scelerisque.neque@nisinibhlacinia.org",
    "phone": "(09) 4379 9847",
    "tagline": "Nunc mauris. Morbi non sapien molestie orci tincidunt",
    "available": "Wednesday",
    "nationality": "Australian",
    "cuisine": "Western ,  Thai,  Vietnamese"
  },
  {
    "name": "Joseph",
    "password": 641,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "laoreet@orci.com",
    "phone": "(02) 8044 8117",
    "tagline": "et magnis dis parturient montes,",
    "available": "Friday",
    "nationality": "European",
    "cuisine": "Western ,  Korean"
  },
  {
    "name": "Neville",
    "password": 559,
    "title": "HR",
    "picture": "URL",
    "email": "eleifend.Cras@dignissim.edu",
    "phone": "(09) 5860 8504",
    "tagline": "Integer tincidunt aliquam arcu.",
    "available": "Thursday",
    "nationality": "Malaysian",
    "cuisine": "Vietnamese ,  Western , Indian"
  },
  {
    "name": "Ira",
    "password": 672,
    "title": "Support Staff",
    "picture": "URL",
    "email": "sit.amet.orci@musDonec.net",
    "phone": "(02) 0425 2598",
    "tagline": "mi lacinia mattis. Integer",
    "available": "Monday ,  Tuesday ,  Wednesday",
    "nationality": "Malaysian",
    "cuisine": "Indian ,  French ,  Korean ,  Thai,  Vietnamese"
  },
  {
    "name": "Lydia",
    "password": 852,
    "title": "HR",
    "picture": "URL",
    "email": "interdum@Praesenteudui.com",
    "phone": "(04) 6806 8493",
    "tagline": "ut cursus luctus, ipsum leo elementum",
    "available": "Monday ,  Tuesday ,  Thursday ,  Friday",
    "nationality": "American",
    "cuisine": "Indian ,  Western ,  Korean ,  Chinese ,  Thai"
  },
  {
    "name": "Tanya",
    "password": 415,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "Sed.eget.lacus@ornaretortor.com",
    "phone": "(08) 1546 2192",
    "tagline": "vel pede blandit congue.",
    "available": "Monday",
    "nationality": "Australian",
    "cuisine": "Korean"
  },
  {
    "name": "Rudyard",
    "password": 154,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "neque.Nullam.nisl@bibendum.org",
    "phone": "(03) 3650 4441",
    "tagline": "fermentum convallis ligula. Donec luctus",
    "available": "Tuesday",
    "nationality": "Indian",
    "cuisine": "French ,  Chinese ,  Korean ,  Western ,  Vietnamese , Indian"
  },
  {
    "name": "Chase",
    "password": 353,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "ornare@quamvel.edu",
    "phone": "(06) 3957 1914",
    "tagline": "nisl elementum purus,",
    "available": "Thursday ,  Wednesday , Monday",
    "nationality": "American",
    "cuisine": "Korean ,  Thai,  Vietnamese ,  French ,  Chinese , Indian"
  },
  {
    "name": "Isabella",
    "password": 738,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "sociosqu@Crasvulputatevelit.edu",
    "phone": "(06) 8173 7399",
    "tagline": "turpis non enim. Mauris quis turpis vitae purus gravida",
    "available": "Thursday ,  Friday,  Tuesday ,  Wednesday , Monday",
    "nationality": "Australian",
    "cuisine": 0
  },
  {
    "name": "Octavia",
    "password": 525,
    "title": "Principal Architect",
    "picture": "URL",
    "email": "in@tinciduntadipiscing.com",
    "phone": "(01) 7449 1821",
    "tagline": "semper",
    "available": "Tuesday ,  Friday, Monday ,  Wednesday",
    "nationality": "Malaysian",
    "cuisine": "Chinese , Indian ,  French ,  Vietnamese"
  },
  {
    "name": "Moana",
    "password": 428,
    "title": "HR",
    "picture": "URL",
    "email": "ligula@posuere.org",
    "phone": "(08) 7233 5520",
    "tagline": "amet, consectetuer adipiscing",
    "available": "Thursday",
    "nationality": "Malaysian",
    "cuisine": 0
  },
  {
    "name": "Kermit",
    "password": 870,
    "title": "Junior Architect",
    "picture": "URL",
    "email": "ipsum@lobortisClass.ca",
    "phone": "(07) 0464 9575",
    "tagline": "nisl",
    "available": 0,
    "nationality": "European",
    "cuisine": "French ,  Chinese ,  Thai,  Korean ,  Vietnamese , Indian ,  Western"
  },
  {
    "name": "Sonia",
    "password": 389,
    "title": "BIM Manager",
    "picture": "URL",
    "email": "leo.Morbi@tristique.co.uk",
    "phone": "(02) 6100 1886",
    "tagline": "ornare, elit elit",
    "available": "Thursday",
    "nationality": "Indian",
    "cuisine": "Thai, Indian ,  French ,  Korean ,  Western"
  },
  {
    "name": "Abra",
    "password": 175,
    "title": "HR",
    "picture": "URL",
    "email": "at.pretium.aliquet@vitae.com",
    "phone": "(01) 9151 9023",
    "tagline": "neque sed dictum eleifend,",
    "available": 0,
    "nationality": "Malaysian",
    "cuisine": "Indian ,  Western ,  Thai,  French ,  Chinese ,  Vietnamese ,  Korean"
  },
  {
    "name": "Shea",
    "password": 587,
    "title": "HR",
    "picture": "URL",
    "email": "lacus@vitae.co.uk",
    "phone": "(09) 8140 0344",
    "tagline": "Aenean euismod",
    "available": 0,
    "nationality": "Malaysian",
    "cuisine": "French ,  Korean , Indian ,  Vietnamese ,  Thai,  Chinese ,  Western"
  }
]

module.exports = dummyUsers; 